### ISSUE TITLE
Change review alert text

### ISSUE THREAD

**Issue by sachinrot** [FYOH/IOS#100]
Change to "Review submitted successfully"
![img_0120 png](https://cloud.githubusercontent.com/assets/9375175/21384368/558713ac-c790-11e6-9dcb-bc437aa151ed.jpg)

**Comment by shrikant-redorange** [comment]
Update Message on review Submit.

![img_1203](https://cloud.githubusercontent.com/assets/23091851/21392494/25daf8a0-c7b6-11e6-895c-1326859e0600.PNG)
