### ISSUE TITLE
Venue description from admin panel

### ISSUE THREAD

**Issue by sachinrot** [FYOH/IOS#109]
I also looked into HTML text designs… in the backend of wordpress when typing in descriptions, we have a “visual” & “text” option. One tab is for actually putting in the HTML code to change the design, the other you should just be able click the options to change the design and the code will automatically be entered. The issue is that the code gets entered in the backend but nothing on the app changes, and we really need to change description writing design because it just looks too plain.

**Comment by chetanohol** [comment]
Basic HTML tags are working, tags which are predefined there are not working like ul,em etc....
