### ISSUE TITLE
Sign up- venue selection

### ISSUE THREAD

**Issue by sachinrot** [FYOH/IOS#117]
When you first sign up as host and select venues. Having a space after the Venues gives a problem and does not pull up the venue. Sometimes people put space and sometimes people don't so we need to make sure that both in the search box in app and when selecting venues people need to pull up the venue if they both put and not put a space after words

**Comment by shrikant-redorange** [comment]
Fixed, now if user add spaces before or after venue name, search result will get display.

![img_1213](https://cloud.githubusercontent.com/assets/23091851/21499645/b35f7fc4-cc5d-11e6-89ff-260c502d3e03.PNG)
