### ISSUE TITLE
Add placeholder image for empty Chat tab

### ISSUE THREAD

**Issue by sachinrot** [FYOH/IOS#124]
add placeholder image as a background when there are no chats to display in chat tab, make something like attached image.
![img_0069 jpg](https://cloud.githubusercontent.com/assets/9375175/21635829/f0e3e64a-d285-11e6-99cb-757e1ca2aacf.jpg)

**Comment by shrikant-redorange** [comment]
![screen shot 2017-01-05 at 8 22 48 pm](https://cloud.githubusercontent.com/assets/23091851/21684969/c28b3284-d385-11e6-9911-cfcb1897d0a3.png)

**Comment by chetanohol** [comment]
Currently image is looking too dark if we make it faint it will look better.
