### ISSUE TITLE
Contact host >> number of people UI change 

### ISSUE THREAD

**Issue by sachinrot** [FYOH/IOS#125]
Client has suggested that we should remove the text box for number of people and do something similar to what expedia app does, see scree shot.See how they add people at bottom of screen shot.
![img_9579 png](https://cloud.githubusercontent.com/assets/9375175/21837676/97585dfe-d7f3-11e6-8458-9d482e03ec67.jpg)

**Comment by shrikant-redorange** [comment]
![screen shot 2017-01-16 at 8 37 30 pm](https://cloud.githubusercontent.com/assets/23091851/21988002/ab92cf48-dc2b-11e6-9dc3-20faffec4d6f.png)
