### ISSUE TITLE
My reviews

### ISSUE THREAD

**Issue by sachinrot** [FYOH/IOS#18]
If you click on the user profile pic who gave you review, the user detail page is loaded. on this page the placeholder image for profile pic is Default.png which has FYOH logo. Please change this to use headshot image of user profile pic. 
![simulator screen shot 11-nov-2016 6 54 36 pm](https://cloud.githubusercontent.com/assets/9375175/20216545/4d4eb47e-a841-11e6-858f-495b0c17076d.png)

**Comment by shrikant-redorange** [comment]
Now replace default image, with headshot image
