### ISSUE TITLE
Setting-Account Settings-Change Password

### ISSUE THREAD

**Issue by chetanohol** [FYOH/IOS#34]
1.Old password and new password should not be same.
2.Show error message if it is same.
3.Currently entered password is visible to user encrypt it

**Comment by shrikant-redorange** [comment]
![simulator screen shot 15-nov-2016 3 45 09 pm](https://cloud.githubusercontent.com/assets/23091851/20301772/bb245ca4-ab4a-11e6-96dc-6e0d0f10fa91.png)
![simulator screen shot 15-nov-2016 3 45 22 pm](https://cloud.githubusercontent.com/assets/23091851/20301771/bb20a35c-ab4a-11e6-9da1-31a2719221ac.png)
