### ISSUE TITLE
Sign Up-Email-My Venues

### ISSUE THREAD

**Issue by chetanohol** [FYOH/IOS#41]
When I select venue page gets disturb (it looks like it move upward, scroll down and then select venue).

**Comment by chetanohol** [comment]
Currently I am able to select 4 venues.

1. First select three venue.
2. Now unchecked two venues.
3. now scroll down list and try to select venues.
4. four venues gets selected.

**Comment by shrikant-redorange** [comment]
Refixed and Manage all Scenario....for selection.

**Comment by sachinrot** [comment]
there is no more animation, client asked us to remove animation so issue is invalidated.
