### ISSUE TITLE
Chat Module

### ISSUE THREAD

**Issue by sachinrot** [FYOH/IOS#50]
Chat Main list: Move latest conversation Row on top of the list like whatsapp.

**Comment by chetanohol** [comment]
When I open keypad last message is not visible, manual scroll up is required

**Comment by shrikant-redorange** [comment]
When I open keypad last message is not visible, manual scroll up is required >>>> This line is not for current issue, but

**Comment by chetanohol** [comment]
Manage all scenario.....
