### ISSUE TITLE
I have entered 140 characters still I have getting error "No more than 140 charcters".

### ISSUE THREAD

**Issue by chetanohol** [FYOH/IOS#61]
![image](https://cloud.githubusercontent.com/assets/23091955/20658409/931ee982-b562-11e6-9617-dae88896e6e3.png)

![image](https://cloud.githubusercontent.com/assets/23091955/20658413/9c3f0164-b562-11e6-859e-0d63a7de4db5.png)

**Comment by chetanohol** [comment]
If I put space then you are increasing character count.....which is right...but when I submit and edit you are removing that spaces which is creating confusion like before submission my status msg was 10 characters in length and after edit it is 6 .....

Expected :- Show status as it is entered.

**Comment by sachinrot** [comment]
again this is the smalled bug can be fixed withing 5 mins, why these things are taking this much time?

**Comment by shrikant-redorange** [comment]
Fixed this for ASCII Characters, still have doubt for special characters, due to which the condition gets failed.
