### ISSUE TITLE
Change contact host popup 

### ISSUE THREAD

**Issue by sachinrot** [FYOH/IOS#72]
change contact host popup to transparent dark grey (like reviews) title: “Select Your Venue” (remove black banner over number pad when typing in “how many people in your party”)…. ⁃ after submitting the text should ONLY read: “Club name, number of people” e.g ‘Warwick, 4 people’
also "how many people in your party"
should be changed to
"How many people are in your party?"

**Comment by chetanohol** [comment]
1. contact popup is not transparent dark gray
2. still that square banner is display on number when typing in.
3.after submitting text appears " Hello Chetan is looking to get...........Test Venue for a party of 6,

**Comment by sachinrot** [comment]
nothing is fixed here Shrikant why did you mark it as fixed?

**Comment by sachinrot** [comment]
"Which Venue" should read "Select Your Venue"
