### ISSUE TITLE
Home page region listing Title problem

### ISSUE THREAD

**Issue by sachinrot** [FYOH/IOS#74]
When there is no image available for some region then FYOH default image is loaded but the region name overlaps the FYOH logo and it looks bad, also region name is white and it doesnt appear. Come up with more smarter solution in this scenario.

**Comment by sachinrot** [comment]
Shrikant, this needs to go away today, this is sitting in the list from last 6 days

**Comment by shrikant-redorange** [comment]
This is fixed, I handle the title text according to image success and failure.

**Comment by chetanohol** [comment]
Still Region name is not visible
