### ISSUE TITLE
App is crashing if give tap on Venue name

### ISSUE THREAD

**Issue by chetanohol** [FYOH/IOS#75]
1. Go to San Fran Region.
2. Click on "Test Venue" 
3. App gets crash.

**Comment by shrikant-redorange** [comment]
i don't get this issue...i checked for all known scenario.

**Comment by chetanohol** [comment]
As we have seen app gets crash if load more venues and again go to top and click on page.

**Comment by chetanohol** [comment]
Still app is crashing ..

**Comment by shrikant-redorange** [comment]
Now check for pull to refresh
