### ISSUE TITLE
app UI consistency for header

### ISSUE THREAD

**Issue by sachinrot** [FYOH/IOS#80]
Make all the navigation bar consistent throughout the app. the navigation bar has back button title and few other components, all of them look differently on some views, please make them consistent so they look same on all views. i have attached image for reference, i want it to look like business listing page header
![1](https://cloud.githubusercontent.com/assets/9375175/20881011/50670748-bb00-11e6-9ea3-9b6c47bf1305.jpg)
![2](https://cloud.githubusercontent.com/assets/9375175/20881012/507d05de-bb00-11e6-8848-3f07ac90149e.jpg)

**Comment by chetanohol** [comment]
1.On region listing page map symbol is center to region name, but on business detail page share symbol is 
not center to region name.(Verify it once)
2.  On business detail page top panel banner is looks gray (slightly different from region listing page.)


![image](https://cloud.githubusercontent.com/assets/23091955/20955727/6db4d426-bc6b-11e6-8334-99c2966c01b0.png)

**Comment by shrikant-redorange** [comment]
1. I adjust the share button layout centrally, please check below screenshot.
2. On business detail page top panel banner is looks gray (slightly different from region listing page.) >>> its requirement for that particular page, to keep same colour.



![simulator screen shot 07-dec-2016 11 14 55 am](https://cloud.githubusercontent.com/assets/23091851/20956197/76c2d010-bc6e-11e6-860e-b8cc88770622.png)
