### ISSUE TITLE
Business Closed 

### ISSUE THREAD

**Issue by sachinrot** [FYOH/IOS#81]
Implement business closed functionality. Final mockup is attached, Mockup has wrong spelling, make sure you write "Closed Today"
![img_0041 png](https://cloud.githubusercontent.com/assets/9375175/20881195/369b9058-bb01-11e6-83fe-d17bb7ff6452.jpg)

**Comment by chetanohol** [comment]
If none of the operational day is selected that venue should be closed, Venue is open only if he has selected operation day.

**Comment by shrikant-redorange** [comment]
if none day will get select, its by default set to closed.
