### ISSUE TITLE
Business detail page: Location on navigation bar is always empty

### ISSUE THREAD

**Issue by sachinrot** [FYOH/IOS#85]
We have Region name and Location name under it on Navigation Bar, i have checked all the businesses in LA section and Vegas, it doesnt load location for any of them.
![2](https://cloud.githubusercontent.com/assets/9375175/20883352/abf20152-bb0b-11e6-9cff-9270b7c80138.jpg)

**Comment by shrikant-redorange** [comment]
Remove subtitle please refer bug no. #87 >>> Remove subtitle on navigation bar on business details page
