### ISSUE TITLE
Load Host list in host tab in chunks of 20 

### ISSUE THREAD

**Issue by sachinrot** [FYOH/IOS#89]

**Comment by chetanohol** [comment]
1. I have 20 hosts in list....when I scroll down page loader gets display....According to me 20 hosts should gets display without loader.

2. Currently on ly 18 host list gets display by default when I scroll down .....other host list gets display but to see list of host loaded at first time I need page refresh (pull to refresh).

**Comment by shrikant-redorange** [comment]
Fixed for next data
