### ISSUE TITLE
Facebook profile pics do not display in chat box for someone who is signed in through Facebook

### ISSUE THREAD

**Issue by sachinrot** [FYOH/IOS#94]

**Comment by shrikant-redorange** [comment]
Add function to upload social picture while signup

See sample screenshot >>> Raj manhotra (HOST) SignUp/Login Via Social.

![screen shot 2016-12-21 at 7 40 15 pm](https://cloud.githubusercontent.com/assets/23091851/21392361/7a92de68-c7b5-11e6-8c7f-7e89735ef937.png)
