### ISSUE TITLE
Choose Venues 2

### ISSUE THREAD

**Issue by sachinrot** [FYOH/IOS#96]
in alert Remove "select business" and have message only display "Every host can select up to 3 venues" 
"Choose your venues" in search box should change to "Please choose the three venues you work with" in black, not gray.
![img_0114 png](https://cloud.githubusercontent.com/assets/9375175/21383487/04348f4c-c78c-11e6-950a-3e32b2b4e8d1.jpg)

**Comment by shrikant-redorange** [comment]
update message

![img_1206](https://cloud.githubusercontent.com/assets/23091851/21393023/a43222f8-c7b8-11e6-87f2-5e787513c1d5.PNG)
