### ISSUE TITLE
account activation notification message 

### ISSUE THREAD

**Issue by sachinrot** [FYOH/IOS#97]
change word  "login to" to "log into"
![img_0115 png](https://cloud.githubusercontent.com/assets/9375175/21383537/43e003a6-c78c-11e6-9a7c-2a36f9fb2251.jpg)

**Comment by shrikant-redorange** [comment]
update account updation message.

![img_1199](https://cloud.githubusercontent.com/assets/23091851/21392236/f62969e4-c7b4-11e6-8a32-454e289fb8d4.PNG)
