### ISSUE TITLE
Contact Host Tab

### ISSUE THREAD

**Issue by sachinrot** [FYOH/IOS#99]
when users don't don’t select number of people in party it shouldnt let them message, should display message instead saying "Please select the number of people in your party," it should not go to message and say "party of 0"

**Comment by shrikant-redorange** [comment]
Update message.

![img_1204](https://cloud.githubusercontent.com/assets/23091851/21392633/c9d1461c-c7b6-11e6-87d8-60b5b3f90c3f.PNG)
